name: Imprime data atual

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual - Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprime data atual
        run: date
  
  imprime_data_windows:
    name: Imprime data atual - Windows
    runs-on: windows-latest
        
    steps:
      - name: Imprime data atual
        run: date
        
  imprime_data_macos:
    name: Imprime data atual - macos
    runs-on: windows-latest
        
    steps:
      - name: Imprime data atual
        run: date
        

  imprime_data_ubumto-latest:
    name: Imprime data atual - ubumto-latest
    runs-on: windows-latest
    needs: 
    - Imprime data atual - Ubuntu
    - Imprime data atual - Windows
    - Imprime data atual - macos
    steps:
      - name: Imprime data atual
        run: date
